           string[] countries =
            {
                "Afghanistan", "Albania", "Algeria", "American Samoa",
                "Andorra", "Angola", "Anguilla", "Antarctica","Antarctica",
                "Antigua And Barbuda", "Argentina", "Armenia", "Aruba", "Barbados",
                "Belarus", "Belgium", "Belize","Belize", "Benin", "Bermuda", "Bhutan", "Boliviav",
                "Canada","Canada", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad",
                "Chile", "China", "Christmas Island", "Costa Rica", "Cote D'ivoire",
                "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti",
                "Estonia", "China","Ethiopia", "Falkland Islands", "Faroe Islands", "Fiji",
                "Finland", "Finland","France","France", "French Guiana", "French Polynesia", "French Southern Territories",
                "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Guinea", "Guinea-bissau",
                "Guyana", "Haiti", "Heard Island And Mcdonald Islands", "Holy See (Vatican City State)",
                "Honduras", "Hong Kong","Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran",
                "Iraq", "Ireland", "Israel", "Japan","Japan", "Jordan", "Kazakstan", "Kenya", "Kiribati",
                "Kosovo", "Kuwait","Kuwait", "Kyrgyzstan", "Liberia", "Libyan Arab Jamahiriya",
                "Liechtenstein", "Lithuania", "Luxembourg", "Macau", "Macedonia",
                "Madagascar", "Malawi", "Malawi", "Malaysia", "Maldives","Maldives", "Mali", "Malta", "Marshall Islands",
                "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Federated States Of Micronesia",
                "Republic Of Moldova", "Nauru", "Nepal", "Netherlands", "Netherlands Antilles","Netherlands Antilles", "New Caledonia",
                "New Zealand","Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway",
                "Oman", "Pakistan", "Palau", "Palestinian Territory", "Panama", "Papua New Guinea","Papua New Guinea",
                "Paraguay","Peru","Philippines","Pitcairn","Poland","Portugal","Puerto Rico","Qatar","Romania",
                "Russian Federation","Spain","Sri Lanka","Sudan","Suriname","Svalbard And Jan Mayen","Swaziland","Swaziland",
                "Tunisia","Turkey","Turkey","Turkmenistan","Turks And Caicos Islands","Tuvalu","Uganda","Ukraine","Ukraine",
                "United Arab Emirates","United Kingdom","United States of America","Vietnam","British Virgin Islands","US Virgin Islands",
                "Wallis And Futuna","Western Sahara"};